receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"
        # cors_allowed_origins:
        #   - "*"

# processors:
#   batch:

exporters:
  logging:
    logLevel: debug
  prometheusremotewrite:
    endpoint: https://633871:eyJrIjoiYzEwZWFjN2ExYjkyZTBiZjQxMTM5OTI1Njc0MGU5ODNiMzFiYWNmYiIsIm4iOiJtb2ppLW5vZGUtdGVzdCIsImlkIjo3MzY2MDd9@prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  prometheus:
    endpoint: "localhost:8889"
    # namespace: "default"
    # const_labels:
    #   label1: value1
    #   'another label': spaced value
    send_timestamps: true
    metric_expiration: 180m
    # resource_to_telemetry_conversion:
    #   enabled: true


service:
  pipelines:
    metrics:
      receivers: [otlp]
      # processors: [batch]
      # exporters: [logging]
      # exporters: [prometheusremotewrite]
      exporters: [prometheus]


# Read API-Key: eyJrIjoiYjlhOTZlYjc0MzFlZTBiZWU0ZGM0ZDUyMzg0NjE5OTU0ZGI2ZmVjMSIsIm4iOiJyZWFkLWFwaS1wcm9tZXRoZXVzIiwiaWQiOjczNjYwN30=
# curl -X GET -k -H 'Content-Type: a_pplication/json' -i 'http://api_key:eyJrIjoiYjlhOTZlYjc0MzFlZTBiZWU0ZGM0ZDUyMzg0NjE5OTU0ZGI2ZmVjMSIsIm4iOiJyZWFkLWFwaS1wcm9tZXRoZXVzIiwiaWQiOjczNjYwN30=@prometheus-prod-01-eu-west-0.grafana.net/api/prom/api/v1/query' --data ''