global:
  scrape_interval: 30s
  scrape_timeout: 20s

# rule_files:
  # - alert.yml

scrape_configs:
  - job_name: da_nodes
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'localhost:8889'